# Generated by Django 5.1.6 on 2025-02-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catname", models.CharField(max_length=200)),
                ("catdes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagetitle", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=250)),
                ("aboutus", models.TextField()),
                ("email", models.EmailField(max_length=200)),
                ("mobilenumber", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posttitle", models.TextField(blank=True)),
                ("postdetails", models.TextField(blank=True)),
                ("status", models.CharField(max_length=50)),
                ("postimage", models.ImageField(upload_to="media/news/images")),
                (
                    "postvideo",
                    models.FileField(
                        blank=True, null=True, upload_to="media/news/videos"
                    ),
                ),
                ("postedby", models.CharField(max_length=50)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updatedby", models.CharField(max_length=50)),
                (
                    "cat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("name", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
                ("status", models.CharField(blank=True, max_length=250)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "news_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.news"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcatname", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="subcategory_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.subcategory"
            ),
        ),
    ]
