# Generated by Django 5.1.6 on 2025-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="postimage",
            field=models.ImageField(blank=True, null=True, upload_to="media/news/"),
        ),
    ]
