# Generated by Django 5.1.6 on 2025-02-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=10,
                null=True,
            ),
        ),
    ]
