# Generated by Django 5.1.6 on 2025-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_news_video_url_alter_news_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="video_url",
        ),
        migrations.AddField(
            model_name="news",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="media/videos/"),
        ),
    ]
