# Generated by Django 5.1.6 on 2025-03-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_news_postvideo_alter_news_postimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("2", "Intern"), ("3", "Reader")], default="2", max_length=50
            ),
        ),
    ]
