# Generated by Django 5.1.6 on 2025-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_news_video_url_news_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=5,
                verbose_name="user type",
            ),
        ),
    ]
