# Generated by Django 5.1.6 on 2025-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_customuser_groups_alter_customuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("2", "reader"), ("1", "intern")], default=1, max_length=50
            ),
        ),
    ]
