# Generated by Django 5.1.6 on 2025-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "intern"), ("2", "reader")], default="1", max_length=50
            ),
        ),
    ]
