# Generated by Django 5.1.6 on 2025-03-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "admin"), ("2", "subadmin")], default="1", max_length=50
            ),
        ),
    ]
