# Generated by Django 5.1.6 on 2025-06-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_customuser_full_name_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="mobile",
        ),
    ]
